version: '3'
services:
  web:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - ${PWD-.}:/app
      - npm_cache:/app/node_modules
    stdin_open: true
    tty: true
volumes:
  npm_cache:
    driver: local
